-- Add all missing columns (camelCase for Prisma/PostgREST)
ALTER TABLE events ADD COLUMN IF NOT EXISTS "eventDate" TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "eventType" TEXT DEFAULT 'wedding';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "qrCode" TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "coupleName" TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "couplePhone" TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE events ADD COLUMN IF NOT EXISTS "photoCount" INTEGER DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "photoGbUsed" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "magicLinkToken" TEXT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "magicLinkTokenExpiry" TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "accessExpiresAt" TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMPTZ;
ALTER TABLE events ADD COLUMN IF NOT EXISTS "guestUploadEnabled" BOOLEAN DEFAULT false;